jobs:
  build: # name of your job
    machine: true # executor type
    steps:
      # Commands run in a Linux virtual machine environment
      - run: echo "Hi I'm on a Container Runner!"

workflows:
  build-workflow:
    jobs:
      - build
