version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: test-circleci/test-circleci
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: docker ps
      - run: docker pull dockerhub.paypalcorp.com/sekharscans/oss:9114dd2
